scheduler:
  window_size: 20
  change_threshold: 0.04
  monitor_critic: true
  monitor_actor: true
  monitor_alpha: false
  min_episodes_per_stage: 100
  max_episodes_per_stage: 250

stages:
  - {name: BBP Fixed Discriminator, opponent_type: bbp_fixed_discriminator, difficulty: tutorial, description: "Opponent uses a fixed BBP spread for the whole episode." , min_episodes_per_stage : 300 , max_episodes_per_stage: 500}

  - {name: BBP Acquisition Predator, opponent_type: bbp_acquisition_predator, difficulty: medium, description: "Opponent aggressively discounts new customers to grow its customer base.", min_episodes_per_stage : 300 , max_episodes_per_stage: 800}

  - {name: BBP Loyalty Harvester, opponent_type: bbp_loyalty_harvester, difficulty: medium, description: "Opponent focuses on extracting profit from established customers." , min_episodes_per_stage : 300 , max_episodes_per_stage: 800}
  
  - {name: BBP Myopic Segment Optimizer, opponent_type: bbp_myopic_segment_optimizer, difficulty: hard, description: "Opponent optimizes both prices myopically using grid search", min_episodes_per_stage : 300  , max_episodes_per_stage: 1000}
