"""
Single-Agent Environment Wrapper for Phase 2 Training.

Wraps the two-agent Hotelling environment for single-agent learning.
The opponent's actions are generated by an OpponentPolicy, making the
environment compatible with standard single-agent RL libraries.

Key Features:
- Gymnasium-compatible interface
- Opponent policy is hidden from learning agent
- Supports both flat and hierarchical observation/action spaces
- Easy swapping of opponent policies for experiments
"""

from typing import Dict, Tuple, Any, Optional, Union, cast
import numpy as np
import gymnasium as gym
from gymnasium import spaces

from env.hotelling_env import HotellingDuopolyEnv
from env.opponent_policies import (
    OpponentPolicy,
    OpponentObservation,
    ConstantOpponentPolicy,
    create_opponent_policy,
    create_preset_opponent,
)
from config.constants import (
    NUM_CONSUMERS,
    EPISODE_LENGTH,
    STRATEGY_CYCLE_LENGTH,
    RANDOM_SEED,
    NUM_STRATEGY_ACTIONS,
    PRICING_ACTION_DIM,
    PRICE_UNIFORM_MIN,
    PRICE_UNIFORM_MAX,
    PRICE_BBP_NEW_MIN,
    PRICE_BBP_NEW_MAX,
    PRICE_BBP_OLD_MIN,
    PRICE_BBP_OLD_MAX,
)


class SingleAgentHotellingEnv(gym.Env):
    """
    Single-agent Gymnasium wrapper for Hotelling duopoly.
    
    Converts the two-agent PettingZoo environment into a single-agent
    Gymnasium environment by using an OpponentPolicy for the second firm.
    
    The learning agent is always firm_0. The opponent (firm_1) is controlled
    by the provided OpponentPolicy.
    
    Observation/Action Modes:
    ========================
    
    1. HIERARCHICAL (default):
       - Observation: Dict with "strategy_controller" and "pricing_controller"
       - Action: Dict with "strategy" (Discrete) and "pricing" (Box)
       
    2. FLAT:
       - Observation: Single Box vector (concatenated SC + PC observations)
       - Action: Single Box vector [strategy_logit, uniform, new, old]
       
    The flat mode is useful for simpler RL algorithms that don't support
    Dict spaces.
    """
    
    metadata = {
        "render_modes": [],
        "name": "single_agent_hotelling_v0"
    }
    
    def __init__(
        self,
        opponent_policy: Optional[OpponentPolicy] = None,
        learning_agent: str = "firm_0",
        num_consumers: int = NUM_CONSUMERS,
        episode_length: int = EPISODE_LENGTH,
        strategy_cycle: int = STRATEGY_CYCLE_LENGTH,
        seed: Optional[int] = RANDOM_SEED,
        flat_observation: bool = False,
        flat_action: bool = False,
    ):
        """
        Initialize single-agent environment.
        
        Args:
            opponent_policy: Policy for opponent (uses ConstantOpponentPolicy if None)
            learning_agent: Which agent learns ("firm_0" or "firm_1")
            num_consumers: Number of consumers in market
            episode_length: Total steps per episode
            strategy_cycle: Steps between strategy decisions
            seed: Random seed
            flat_observation: If True, flatten observation to single vector
            flat_action: If True, use flat action space
        """
        super().__init__()
        
        # Validate learning agent
        assert learning_agent in ["firm_0", "firm_1"], \
            f"learning_agent must be 'firm_0' or 'firm_1', got {learning_agent}"
        
        self.learning_agent = learning_agent
        self.opponent_agent = "firm_1" if learning_agent == "firm_0" else "firm_0"
        
        # Create underlying two-agent environment
        self._env = HotellingDuopolyEnv(
            num_consumers=num_consumers,
            episode_length=episode_length,
            strategy_cycle=strategy_cycle,
            seed=seed,
        )
        
        # Store parameters
        self.num_consumers = num_consumers
        self.episode_length = episode_length
        self.strategy_cycle = strategy_cycle
        self.seed_value = seed
        self.flat_observation = flat_observation
        self.flat_action = flat_action
        
        # Set up opponent policy
        if opponent_policy is None:
            self.opponent_policy = ConstantOpponentPolicy()
        else:
            self.opponent_policy = opponent_policy
        
        # Define observation and action spaces
        self._setup_spaces()
        
        # Track timestep for opponent observation
        self._timestep = 0
    
    def _setup_spaces(self):
        """Set up observation and action spaces based on mode."""
        # Get base spaces from underlying environment
        base_obs_space = self._env.observation_spaces[self.learning_agent]
        base_action_space = self._env.action_spaces[self.learning_agent]
        
        if self.flat_observation:
            # Flatten observation space
            self.observation_space = self._flatten_obs_space(base_obs_space)
        else:
            # Use hierarchical observation space
            self.observation_space = base_obs_space
        
        if self.flat_action:
            # Flat action: [strategy_continuous, uniform, new, old]
            # Strategy is continuous [0, 1], threshold at 0.5 to get discrete
            self.action_space = spaces.Box(
                low=0.0,
                high=1.0,
                shape=(1 + PRICING_ACTION_DIM,),  # strategy + pricing
                dtype=np.float32
            )
        else:
            # Use hierarchical action space
            self.action_space = base_action_space
    
    def _flatten_obs_space(self, obs_space: spaces.Space) -> spaces.Box:
        """Flatten hierarchical observation space to single Box."""
        # Calculate total dimension
        total_dim = 0
        
        # Cast to Dict for type checker (we know it's a Dict space)
        dict_space = cast(spaces.Dict, obs_space)
        
        # Strategy controller observations
        sc_space = cast(spaces.Dict, dict_space["strategy_controller"])
        for key, space in sc_space.items():
            if isinstance(space, spaces.Box):
                total_dim += int(np.prod(space.shape))
            elif isinstance(space, spaces.Discrete):
                total_dim += 1
        
        # Pricing controller observations
        pc_space = cast(spaces.Dict, dict_space["pricing_controller"])
        for key, space in pc_space.items():
            if isinstance(space, spaces.Box):
                total_dim += int(np.prod(space.shape))
            elif isinstance(space, spaces.Discrete):
                total_dim += 1
        
        return spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(total_dim,),
            dtype=np.float32
        )
    
    def _flatten_observation(self, obs: Dict) -> np.ndarray:
        """Flatten hierarchical observation to vector."""
        flat_obs = []
        
        # Strategy controller observations (ordered by key for consistency)
        sc_obs = obs["strategy_controller"]
        for key in sorted(sc_obs.keys()):
            value = sc_obs[key]
            if isinstance(value, np.ndarray):
                flat_obs.extend(value.flatten())
            else:
                flat_obs.append(float(value))
        
        # Pricing controller observations
        pc_obs = obs["pricing_controller"]
        for key in sorted(pc_obs.keys()):
            value = pc_obs[key]
            if isinstance(value, np.ndarray):
                flat_obs.extend(value.flatten())
            else:
                flat_obs.append(float(value))
        
        return np.array(flat_obs, dtype=np.float32)
    
    def _convert_flat_action(self, flat_action: np.ndarray) -> Dict[str, Any]:
        """Convert flat action to hierarchical format."""
        # First element is strategy (threshold at 0.5)
        strategy = 1 if flat_action[0] > 0.5 else 0
        
        # Remaining elements are pricing
        pricing = flat_action[1:1+PRICING_ACTION_DIM].astype(np.float32)
        
        return {
            "strategy": strategy,
            "pricing": pricing
        }
    
    def _get_opponent_observation(self, raw_obs: Dict) -> OpponentObservation:
        """Create opponent observation from raw environment observation."""
        return OpponentObservation.from_raw_observation(
            raw_obs,
            timestep=self._timestep,
            episode_length=self.episode_length
        )
    
    def reset(
        self,
        seed: Optional[int] = None,
        options: Optional[Dict] = None
    ) -> Tuple[Union[Dict, np.ndarray], Dict]:
        """
        Reset environment for new episode.
        
        Args:
            seed: Random seed
            options: Additional options
            
        Returns:
            observation, info
        """
        # Reset opponent policy
        self.opponent_policy.reset(seed=seed)
        
        # Reset underlying environment
        observations, infos = self._env.reset(seed=seed, options=options)
        
        # Reset timestep
        self._timestep = 0
        
        # Get learning agent's observation
        obs = observations[self.learning_agent]
        info = infos[self.learning_agent]
        
        # Add opponent info
        info["opponent_policy"] = repr(self.opponent_policy)
        
        if self.flat_observation:
            obs = self._flatten_observation(obs)
        
        return obs, info
    
    def step(
        self,
        action: Union[Dict[str, Any], np.ndarray]
    ) -> Tuple[Union[Dict, np.ndarray], float, bool, bool, Dict]:
        """
        Execute one environment step.
        
        Args:
            action: Learning agent's action
            
        Returns:
            observation, reward, terminated, truncated, info
        """
        # Convert flat action if needed
        if self.flat_action and isinstance(action, np.ndarray):
            action = self._convert_flat_action(action)
        
        # Get opponent's observation from last state
        # (opponent sees what learning agent saw before acting)
        opponent_raw_obs = self._env._get_observation(self.opponent_agent)
        opponent_obs = self._get_opponent_observation(opponent_raw_obs)
        
        # Get opponent's action from policy
        opponent_action = self.opponent_policy.get_action(opponent_obs)
        
        # Combine actions
        actions = {
            self.learning_agent: action,
            self.opponent_agent: opponent_action
        }
        
        # Step underlying environment
        observations, rewards, terminations, truncations, infos = self._env.step(actions)
        
        # Increment timestep
        self._timestep += 1
        
        # Extract learning agent's results
        obs = observations[self.learning_agent]
        reward = rewards[self.learning_agent]
        terminated = terminations[self.learning_agent]
        truncated = truncations[self.learning_agent]
        info = infos[self.learning_agent]
        
        # Add opponent info
        info["opponent_reward"] = rewards[self.opponent_agent]
        info["opponent_regime"] = self._env.regimes[self.opponent_agent]
        info["opponent_policy"] = type(self.opponent_policy).__name__
        
        if self.flat_observation:
            obs = self._flatten_observation(obs)
        
        return obs, reward, terminated, truncated, info
    
    def render(self):
        """Render environment (not implemented)."""
        return self._env.render()
    
    def close(self):
        """Close environment."""
        return self._env.close()
    
    def set_opponent_policy(self, policy: OpponentPolicy):
        """
        Change opponent policy.
        
        Useful for curriculum learning or policy evaluation.
        
        Args:
            policy: New opponent policy
        """
        self.opponent_policy = policy
    
    @property
    def unwrapped(self):
        """Return underlying environment."""
        return self._env


# =============================================================================
# CONVENIENCE FACTORY FUNCTIONS
# =============================================================================

def make_single_agent_env(
    opponent: Union[str, OpponentPolicy] = "passive_uniform",
    flat: bool = False,
    **env_kwargs
) -> SingleAgentHotellingEnv:
    """
    Factory function to create single-agent environment.
    
    Args:
        opponent: Opponent policy (preset name string or OpponentPolicy instance)
        flat: If True, use flat observation and action spaces
        **env_kwargs: Additional arguments for environment
        
    Returns:
        SingleAgentHotellingEnv instance
        
    Examples:
        # Using preset opponent
        env = make_single_agent_env("passive_uniform")
        
        # Using custom opponent
        from env.opponent_policies import RuleBasedOpponentPolicy
        policy = RuleBasedOpponentPolicy(base_uniform_price=2.0)
        env = make_single_agent_env(policy)
        
        # Flat spaces for simpler algorithms
        env = make_single_agent_env("passive_bbp", flat=True)
    """
    # Create opponent policy
    if isinstance(opponent, str):
        opponent_policy = create_preset_opponent(opponent)
    else:
        opponent_policy = opponent
    
    return SingleAgentHotellingEnv(
        opponent_policy=opponent_policy,
        flat_observation=flat,
        flat_action=flat,
        **env_kwargs
    )


def make_curriculum_env(
    opponent_schedule: list,
    **env_kwargs
) -> SingleAgentHotellingEnv:
    """
    Create environment with curriculum of opponents.
    
    Returns environment with first opponent. Use set_opponent_policy()
    to advance through curriculum.
    
    Args:
        opponent_schedule: List of opponent preset names or policies
        **env_kwargs: Additional arguments for environment
        
    Returns:
        SingleAgentHotellingEnv with first opponent
        
    Example:
        schedule = ["passive_uniform", "reactive_uniform", "price_matcher"]
        env = make_curriculum_env(schedule)
        
        # Train, then advance
        env.set_opponent_policy(create_preset_opponent("reactive_uniform"))
    """
    if not opponent_schedule:
        raise ValueError("opponent_schedule must not be empty")
    
    first_opponent = opponent_schedule[0]
    return make_single_agent_env(opponent=first_opponent, **env_kwargs)


# =============================================================================
# REGISTRATION (optional, for gym.make())
# =============================================================================

def register_envs():
    """Register environments with Gymnasium."""
    from gymnasium.envs.registration import register
    
    # Register base single-agent environment
    register(
        id="HotellingSingleAgent-v0",
        entry_point="env.single_agent_env:SingleAgentHotellingEnv",
        max_episode_steps=EPISODE_LENGTH,
    )


if __name__ == "__main__":
    # Quick test
    print("Testing SingleAgentHotellingEnv...")
    
    # Test with preset opponent
    env = make_single_agent_env("passive_uniform")
    obs, info = env.reset()
    print(f"Observation keys: {obs.keys() if isinstance(obs, dict) else obs.shape}")
    print(f"Action space: {env.action_space}")
    
    # Take a step with random action
    action = env.action_space.sample()
    obs, reward, terminated, truncated, info = env.step(action)
    print(f"Reward: {reward:.4f}")
    print(f"Info: {info}")
    
    # Test flat mode
    print("\nTesting flat mode...")
    env_flat = make_single_agent_env("reactive_uniform", flat=True)
    obs_flat, _ = env_flat.reset()
    print(f"Flat observation shape: {obs_flat.shape if isinstance(obs_flat, np.ndarray) else 'N/A'}")
    print(f"Flat action space: {env_flat.action_space}")
    
    action = env_flat.action_space.sample()
    obs_flat, reward, _, _, info = env_flat.step(action)
    print(f"Reward: {reward:.4f}")
    
    print("\nAll tests passed!")
